### ISSUE TITLE
add topic aoc-2021-in-fortran

### ISSUE THREAD

**Issue by Beliavsky** [wiremoons/AdventOfCode2021#1]
4 other repos use the topic aoc-2021-in-fortran . Using it would make it easier to find.

**Comment by wiremoons** [comment]
Added - thanks for the suggestion @Beliavsky

**Comment by Beliavsky** [comment]
You don't need the "topic" in topic-aoc-2021-in-fortran :).

**Comment by wiremoons** [comment]
Good point - bit too literal due over zealous cutting and pasting. Corrected now - thanks for letting me know :)
